### ISSUE TITLE
🐋🐛 Image is missing vc_redist needed for certain python packages

### ISSUE THREAD

**Issue by jsnel** [s-weigand/uv-windows-docker#1]
I found that when trying to import certain python packages (e.g. matplotlib) an error is raised which appears to boil down to some missing DLLS.

## Minimal reproduction

Start an interactive powershell with the server image.

```pwsh
docker run -it --rm ghcr.io/s-weigand/uv-windows:0.5.1-server powershell
```

Then use uv to create a venv (tested to reproduce for 3.10 and 3.13).

```powershell
uv venv
uv pip install matplotlib
.venv/Scripts/activate
# OR .\.venv\Scripts\Activate.ps1
python -c 'import matplotlib'
```

And observe an error `ImportError: DLL load failed while importing _cext: The specified module could not be found.` (details below).

<details>
<summary>full error - click to expand</summary>
<pre>
(.venv) PS C:\> python -c 'import matplotlib'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import matplotlib
  File "C:\.venv\Lib\site-packages\matplotlib\__init__.py", line 263, in <module>
    _check_versions()
    ~~~~~~~~~~~~~~~^^
  File "C:\.venv\Lib\site-packages\matplotlib\__init__.py", line 257, in _check_versions
    module = importlib.import_module(modname)
  File "C:\Users\ContainerAdministrator\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86_64-none\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\.venv\Lib\site-packages\kiwisolver\__init__.py", line 8, in <module>
    from ._cext import (
    ...<8 lines>...
    )
ImportError: DLL load failed while importing _cext: The specified module could not be found.
</pre>
</details>

## Workaround
For an in-session workaround we can run:

```powershell
$ProgressPreference = 'SilentlyContinue'

Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "C:\vc_redist.x64.exe"

Start-Process -FilePath "C:\vc_redist.x64.exe" -ArgumentList "/install", "/quiet", "/norestart" -Wait

# to test (should be no error now):
python -c 'import matplotlib'
```

## Proposed fix

A more permanent fix would be to bake the vc_redist into the image, something along these lines:

```DockerFile
RUN $vcRedistUrl='https://aka.ms/vs/17/release/vc_redist.x64.exe'; `
    $installerPath='C:\vc_redist.x64.exe'; `
    Invoke-WebRequest -Uri $vcRedistUrl -OutFile $installerPath -UseBasicParsing; `
    Start-Process -FilePath $installerPath -ArgumentList '/install', '/quiet', '/norestart' -NoNewWindow -Wait; `
    Remove-Item -Path $installerPath -Force
```

## Limitation

This will not fix issues related to other DLLs which Python packages may implicitly depend on, additional it will 'pollute' the path the stuff of vc_redist.x64.exe v17, but this appears to be a necessary evil.

**Comment by jsnel** [comment]
Following reviewer suggestion changing 
```diff
- Invoke-WebRequest -Uri $vcRedistUrl -OutFile $installerPath -UseBasicParsing; `
+ (New-Object System.Net.WebClient).DownloadFile($vcRedistUrl, $installerPath); `
```
in the proposed solution.
